title: Qi (Emily) Qiu
logo: EmilyQiu720/EmilyQiu720.github.io/blob/main/headshot.jpg
description: Analytics Students at the University of California, Berkeley
#show_downloads: true
theme: jekyll-theme-minimal
